### ISSUE TITLE
Training and Testing issues

### ISSUE THREAD

**Issue by sandhyalaxmiK** [ly015/intrinsic_flow#7]
Hi ly015. Thanks for keeping the repository public available. Currently i am also working on same concept.
I have some doubts
1. How can we test the flow_regression_module.py ??
2. Can i train with my own data with some other segmentation concept like "https://github.com/Engineering-Course/CIHP_PGN"?
3. How to test for posetranser_0.1  (dual)?
with hmr, now i am able to create visibility and flow_maps for my own data. But struck at segmentation. So can i use above mentioned segmentation??  
Your help is more helpful to me to go further.

Thanks & Regards,
SandhyaLaxmi

**Comment by ly015** [comment]
Hi SandhyaLaxmi. Thanks for being interested in our work. 

For the Q1, you can use it like `python ./scripts/flow_regression_module.py --gpu_ids 0 --id model_id`. Also, train_flow_regression_module.py will perform testing and output testing information after each training epoch.

For Q2, I think other segmentation data will also help. The segmentation information is used in the training of the flow regression module to penalize pixels warped to incorrect regions, which we think is like hard negative mining. The reason we use SMPL to generate segmentation data instead of using other segmentation model/dataset is to avoid involving extra knowledge.

For Q3, you can test pose_transfer_0.1 just like other model by `python scripts/test_pose_transfer.py --gpu_ids 0 --id PoseTransfer_0.1 --which_epoch best --save_output`. Please note that pose_transfer_0.1 has a normal U-Net architecture without a dual encoder.
